// file: internals/features/academics/terms/model/academic_term_model.go
package model

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// AcademicTermModel merepresentasikan tabel `academic_terms`
type AcademicTermModel struct {
	AcademicTermsID           uuid.UUID      `json:"academic_terms_id"            gorm:"column:academic_terms_id;type:uuid;default:gen_random_uuid();primaryKey"`
	AcademicTermsMasjidID     uuid.UUID      `json:"academic_terms_masjid_id"     gorm:"column:academic_terms_masjid_id;type:uuid;not null"`

	AcademicTermsAcademicYear string         `json:"academic_terms_academic_year" gorm:"column:academic_terms_academic_year;type:text;not null"` // ex: "2025/2026"
	AcademicTermsName         string         `json:"academic_terms_name"          gorm:"column:academic_terms_name;type:text;not null"`          // "Ganjil" | "Genap" | ...

	AcademicTermsStartDate    time.Time      `json:"academic_terms_start_date"    gorm:"column:academic_terms_start_date;type:timestamptz;not null"`
	AcademicTermsEndDate      time.Time      `json:"academic_terms_end_date"      gorm:"column:academic_terms_end_date;type:timestamptz;not null"`
	AcademicTermsIsActive     bool           `json:"academic_terms_is_active"     gorm:"column:academic_terms_is_active;not null;default:true"`

	// generated by DB, read-only di GORM
	AcademicTermsPeriod       *string        `json:"academic_terms_period,omitempty" gorm:"column:academic_terms_period;type:daterange;->"`

	AcademicTermsCreatedAt    time.Time      `json:"academic_terms_created_at"    gorm:"column:academic_terms_created_at;type:timestamptz;not null;autoCreateTime"`
	AcademicTermsUpdatedAt    time.Time      `json:"academic_terms_updated_at"    gorm:"column:academic_terms_updated_at;type:timestamptz;not null;autoUpdateTime"`
	AcademicTermsDeletedAt    gorm.DeletedAt `json:"academic_terms_deleted_at,omitempty" gorm:"column:academic_terms_deleted_at;type:timestamptz;index"`
}

func (AcademicTermModel) TableName() string { return "academic_terms" }
